# Investment Case Study
Team Members - Balakrishna, Bishnu, Deepak and Basavesh

Checkpoint 1: Data Cleaning 1

   1. Load the companies and rounds data (provided on the previous page) into two data frames and name them companies and rounds2 respectively.
   
   2. Table 1.1: The table below is just for reference â€” you need to fill out the spreadsheet which is attached in the download section. This holds true for all the tables.

In [49]:
# Supress Warnings

import warnings
warnings.filterwarnings('ignore')

In [50]:
# Import the numpy and pandas packages

import numpy as np
import pandas as pd

In [51]:
# Loading first data fromes using pandas import function.
# Companies.txt takes tab as seperate
# using encoding to consider european standard charsets if any and refiltering to remove encoding issue
companies = pd.read_csv('companies.txt' , sep='	', encoding = "ISO-8859-1")
companies['permalink']=companies.permalink.str.encode('utf-8').str.decode('ascii','ignore')
companies['name']=companies.name.str.encode('utf-8').str.decode('ascii','ignore')
companies

,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at
0,/Organization/-Fame,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN
1,/Organization/-Qounter,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014
2,/Organization/-The-One-Of-Them-Inc-,"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps|Games|Mobile,operating,NaN,NaN,NaN,NaN,NaN
3,/Organization/0-6-Com,0-6.com,http://www.0-6.com,Curated Web,operating,CHN,22,Beijing,Beijing,01-01-2007
4,/Organization/004-Technologies,004 Technologies,http://004gmbh.de/en/004-interact,Software,operating,USA,IL,"Springfield, Illinois",Champaign,01-01-2010
5,/Organization/01Games-Technology,01Games Technology,http://www.01games.hk/,Games,operating,HKG,NaN,Hong Kong,Hong Kong,NaN
6,/Organization/0Ndine-Biomedical-Inc,Ondine Biomedical Inc.,http://ondinebio.com,Biotechnology,operating,CAN,BC,Vancouver,Vancouver,01-01-1997
7,/Organization/0Xdata,H2O.ai,http://h2o.ai/,Analytics,operating,USA,CA,SF Bay Area,Mountain View,01-01-2011
8,/Organization/1,One Inc.,http://whatis1.com,Mobile,operating,USA,CA,SF Bay Area,San Francisco,01-08-2011
9,/Organization/1-2-3-Listo,"1,2,3 Listo",http://www.123listo.com,E-Commerce,operating,CHL,12,Santiago,Las Condes,01-01-2012
10,/Organization/1-4-All,1-4 All,NaN,Entertainment|Games|Software,operating,USA,NC,NC - Other,Connellys Springs,NaN
11,/Organization/1-618-Technology,1.618 Technology,http://www.Homeandcondogallery.com,Networking|Real Estate|Web Hosting,operating,USA,FL,Orlando,Orlando,07-12-2013
12,/Organization/1-800-Dentist,1-800-DENTIST,http://www.1800dentist.com,Health and Wellness,operating,USA,CA,Los Angeles,Los Angeles,01-01-1986
13,/Organization/1-800-Doctors,1-800-DOCTORS,http://1800doctors.com,Health and Wellness,operating,USA,NJ,Newark,Iselin,01-01-1984
14,/Organization/1-800-Publicrelations-Inc-,"1-800-PublicRelations, Inc.",http://www.1800publicrelations.com,Internet Marketing|Media|Public Relations,operating,USA,NY,New York City,New York,24-10-2013
15,/Organization/1-Mainstream,1 Mainstream,http://www.1mainstream.com,Apps|Cable|Distribution|Software,acquired,USA,CA,SF Bay Area,Cupertino,01-03-2012
16,/Organization/1-Of-99,1 of 99,NaN,Entertainment|Games,operating,USA,CA,SF Bay Area,Mountain View,01-12-2014
17,/Organization/10-20-Media,10-20 Media,http://www.10-20media.com,E-Commerce,operating,USA,MD,Baltimore,Woodbine,01-01-2001
18,/Organization/10-Minutes-With,10 Minutes With,http://10minuteswith.com,Education,operating,GBR,H9,London,London,01-01-2013
19,/Organization/1000-Corks,1000 Corks,http://1000corks.com,Search,operating,USA,OR,"Portland, Oregon",Lake Oswego,01-01-2008
20,/Organization/1000-Markets,1000 Markets,http://www.1000markets.com,Art|E-Commerce|Marketplaces,acquired,USA,WA,Seattle,Seattle,01-01-2009
21,/Organization/1000Chi,Beijing 1000CHI Software Technology,http://www.1000chi.com/,Mobile,operating,NaN,NaN,NaN,NaN,01-01-2008
22,/Organization/1000Lookz,1000Lookz,http://1000lookz.com,Beauty,operating,IND,25,Chennai,Chennai,01-01-2008
23,/Organization/1000Memories,1000memories,http://1000memories.com,Curated Web,acquired,USA,CA,SF Bay Area,San Francisco,01-07-2010
24,/Organization/1000Museums-Com,1000museums.com,http://www.1000museums.com,Curated Web,operating,USA,MA,MA - Other,Lenox,01-01-2008
25,/Organization/1001-Menus,ZenChef,http://zenchef.com/en/,Local Businesses|Restaurants,operating,FRA,A8,Paris,Paris,20-11-2010
26,/Organization/1001Pharmacies-Com,1001pharmacies.com,http://www.1001pharmacies.com/,Cosmetics|Marketplaces,operating,FRA,A9,Montpellier,Montpellier,01-01-2012
27,/Organization/1006-Tv,1006.tv,http://www.1006.tv/,Games|Media,operating,CHN,22,Beijing,Beijing,01-01-2009
28,/Organization/100Du-Tv,100du.tv,http://www.100du.com,Hospitality,operating,CHN,23,Shanghai,Shanghai,NaN
29,/Organization/100E-Com,100e.com,http://www.100e.com,Education,operating,CHN,22,Beijing,Beijing,NaN
...,...,...,...,...,...,...,...,...,...,...
66338,/Organization/Zykis,Zykis,http://zykis.com,Automotive|Data Security|Education|Kids|Portal...,closed,USA,CA,Anaheim,Irvine,27-10-2006
66339,/Organization/Zylie-The-Bear,Zylie the Bear,http://zyliethebear.com,E-Commerce,operating,USA,CT,Hartford,Greenwich,01-01-2009
66340,/Organization/Zylun-Staffing,Zylun Staffing,http://www.zylun.com,Software,operating,USA,UT,Salt Lake City,Lehi,01-01-2010
66341,/Organization/Zyme-Solutions,Zyme Solutions,http://www.zymesolutions.com,Hardware|Hardware + Software,operating,USA,CA,SF Bay Area,Redwood Shores,01-01-2004
66342,/Organization/Zymergen,Zymergen,http://www.zymergen.com,Biotechnology,operating,USA,CA,SF Bay Area,Emeryville,01-01-2013
66343,/Organization/Zymetis,Zymetis,http://www.zymetis.com,Biotechnology,closed,USA,MD,"Washington, D.C.",College Park,01-01-2006
66344,/Organization/Zymeworks,Zymeworks,http://zymeworks.com,Biotechnology,operating,CAN,BC,Vancouver,Vancouver,01-04-2004
66345,/Organization/Zymochem,Zymochem,http://www.zymochem.com,Specialty Chemicals,operating,USA,CA,SF Bay Area,San Francisco,01-05-2013
66346,/Organization/Zympi,Zympi,http://www.zympi.com,Mobile|Networking|Web Hosting,operating,USA,CA,Ontario - Inland Empire,Redlands,03-09-2010
66347,/Organization/Zymr-Inc-,"Zymr, Inc.",http://www.zymr.com,Android|Apps|Cloud Computing|Cloud Infrastruct...,operating,USA,CA,SF Bay Area,Santa Clara,NaN
66348,/Organization/Zyncd,Zyncd,http://www.zyncd.com,Crowdsourcing|Knowledge Management,operating,GBR,H9,London,London,01-01-2014
66349,/Organization/Zyncro,Zyncro,http://www.zyncro.com,Cloud Computing|Enterprise 2.0|Enterprise Soft...,acquired,ESP,56,Barcelona,Barcelona,01-09-2009
66350,/Organization/Zynerba-Pharmaceuticals,Zynerba Pharmaceuticals,http://zynerba.com,Pharmaceuticals,ipo,USA,PA,Philadelphia,Radnor,01-01-2014
66351,/Organization/Zynergy-Projects-Services,Zynergy Projects & Services,http://www.zynergygroup.net/,Clean Technology,operating,IND,25,Chennai,Chennai,NaN
66352,/Organization/Zynga,Zynga,http://www.zynga.com,Facebook Applications|Games|Networking|Technology,ipo,USA,CA,SF Bay Area,San Francisco,01-07-2007
66353,/Organization/Zyngenia,Zyngenia,http://www.zyngenia.com,Biotechnology,operating,USA,MD,"Washington, D.C.",Gaithersburg,01-01-2008
66354,/Organization/Zynstra,Zynstra,http://www.zynstra.com,Software,operating,GBR,A4,Bath,Bath,30-11-2011
66355,/Organization/Zyomyx-Inc,ZYOMYX,http://www.zyomyx.com,Biotechnology,operating,USA,MO,MO - Other,Fremont,01-01-1998
66356,/Organization/Zype,Zype,http://www.zype.com,Cloud Computing|Mobile Advertising|Video|Video...,operating,USA,NY,New York City,New York,01-01-2013
66357,/Organization/Zypsee,Whisk (formerly Zypsee),http://whisk.me,Public Transportation,operating,USA,NY,New York City,New York,01-01-2011
66358,/Organization/Zyraz-Technology,Zyraz Technology,http://www.zyraz.com,Biotechnology,closed,MYS,14,MYS - Other,Damansara New Village,01-01-1994
66359,/Organization/Zyrra,Zyrra,http://www.zyrra.com,E-Commerce,operating,USA,MA,Boston,Cambridge,NaN
66360,/Organization/Zystor,Zystor,http://www.zystor.com,Biotechnology,acquired,USA,WI,Milwaukee,Milwaukee,NaN
66361,/Organization/Zytoprotec,Zytoprotec,http://www.zytoprotec.com,Biotechnology,operating,AUT,3,Vienna,Gerasdorf Bei Wien,01-01-2007
66362,/Organization/Zzish,Zzish,http://www.zzish.com,Analytics|Android|Developer APIs|Education|Gam...,operating,GBR,H9,London,London,28-01-2014
66363,/Organization/Zznode-Science-And-Technology-Co...,ZZNode Science and Technology,http://www.zznode.com,Enterprise Software,operating,CHN,22,Beijing,Beijing,NaN
66364,/Organization/Zzzzapp-Com,Zzzzapp Wireless ltd.,http://www.zzzzapp.com,Advertising|Mobile|Web Development|Wireless,operating,HRV,15,Split,Split,13-05-2012
66365,/Organization/Eron,ERON,http://www.aeron.hu/,NaN,operating,NaN,NaN,NaN,NaN,01-01-2011
66366,/Organization/Asys-2,asys,http://www.oasys.io/,Consumer Electronics|Internet of Things|Teleco...,operating,USA,CA,SF Bay Area,San Francisco,01-01-2014
66367,/Organization/Novatiff-Reklam-Ve-TanTM-Hizmetl...,novatiff Reklam ve Tantm Hizmetleri Tic,http://inovatiff.com,Consumer Goods|E-Commerce|Internet,operating,NaN,NaN,NaN,NaN,NaN

In [52]:
# Loading second data fromes using pandas import function.
# rounds2.csv takes tab as seperate
# using encoding to consider european standard charsets if any and refiltering to remove encoding issues
rounds2 = pd.read_csv('rounds2.csv' , sep=',', encoding = "ISO-8859-1")
rounds2['company_permalink']=rounds2.company_permalink.str.encode('utf-8').str.decode('ascii','ignore')
rounds2

,company_permalink,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
0,/organization/-fame,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,B,05-01-2015,10000000.0
1,/ORGANIZATION/-QOUNTER,/funding-round/22dacff496eb7acb2b901dec1dfe5633,venture,A,14-10-2014,NaN
2,/organization/-qounter,/funding-round/b44fbb94153f6cdef13083530bb48030,seed,NaN,01-03-2014,700000.0
3,/ORGANIZATION/-THE-ONE-OF-THEM-INC-,/funding-round/650b8f704416801069bb178a1418776b,venture,B,30-01-2014,3406878.0
4,/organization/0-6-com,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,A,19-03-2008,2000000.0
5,/ORGANIZATION/004-TECHNOLOGIES,/funding-round/1278dd4e6a37fa4b7d7e06c21b3c1830,venture,NaN,24-07-2014,NaN
6,/organization/01games-technology,/funding-round/7d53696f2b4f607a2f2a8cbb83d01839,undisclosed,NaN,01-07-2014,41250.0
7,/ORGANIZATION/0NDINE-BIOMEDICAL-INC,/funding-round/2b9d3ac293d5cdccbecff5c8cb0f327d,seed,NaN,11-09-2009,43360.0
8,/organization/0ndine-biomedical-inc,/funding-round/954b9499724b946ad8c396a57a5f3b72,venture,NaN,21-12-2009,719491.0
9,/ORGANIZATION/0XDATA,/funding-round/383a9bd2c04f7038bb543ccef5ba3eae,seed,NaN,22-05-2013,3000000.0
10,/organization/0xdata,/funding-round/3bb2ee4a2d89251a10aaa735b1180e44,venture,B,09-11-2015,20000000.0
11,/ORGANIZATION/0XDATA,/funding-round/ae2a174c06517c2394aed45006322a7e,venture,NaN,03-01-2013,1700000.0
12,/organization/0xdata,/funding-round/e1cfcbe1bdf4c70277c5f29a3482f24e,venture,A,19-07-2014,8900000.0
13,/ORGANIZATION/1,/funding-round/03b975068632eba5bfdb937ec8c07a68,seed,NaN,05-02-2014,150000.0
14,/organization/1,/funding-round/5de6d8828aef7d925d97918d15727670,undisclosed,NaN,05-02-2013,NaN
15,/ORGANIZATION/1,/funding-round/e82464f22241715dd1a6c77241055ed1,seed,NaN,20-07-2011,1000050.0
16,/organization/1-2-3-listo,/funding-round/6de4609e894495105bc791ed64361288,seed,NaN,18-02-2013,40000.0
17,/ORGANIZATION/1-4-ALL,/funding-round/e97a192e13ea0ee3c4f71136b4f3ec16,equity_crowdfunding,NaN,21-04-2013,NaN
18,/organization/1-618-technology,/funding-round/83b8f4c7d37ecef5e001a5e953bf461a,equity_crowdfunding,NaN,22-01-2014,NaN
19,/ORGANIZATION/1-800-DENTIST,/funding-round/5274aacc211163fc7c86539ce94bbacc,undisclosed,NaN,19-08-2010,NaN
20,/organization/1-800-doctors,/funding-round/9eb8c7790a0c200d79e75785d1c4aa12,convertible_note,NaN,02-03-2011,1750000.0
21,/ORGANIZATION/1-800-PUBLICRELATIONS-INC-,/funding-round/11c228f58831bc7ed337ef69ecc560c2,private_equity,NaN,01-02-2015,6000000.0
22,/organization/1-mainstream,/funding-round/b952cbaf401f310927430c97b68162ea,venture,NaN,17-03-2015,5000000.0
23,/ORGANIZATION/1-OF-99,/funding-round/b5c811f561cfb5701cd5b1762120bbc3,convertible_note,NaN,13-12-2014,100000.0
24,/organization/10-20-media,/funding-round/436874dc54b54460f99f44c06e50990a,debt_financing,NaN,11-01-2011,800000.0
25,/ORGANIZATION/10-20-MEDIA,/funding-round/8025ee9c11a586eac4a234ddec7beb30,debt_financing,NaN,18-06-2009,500000.0
26,/organization/10-20-media,/funding-round/a884bf8326b9fd59789c0f74a28dbc3b,debt_financing,NaN,28-12-2011,500000.0
27,/ORGANIZATION/10-20-MEDIA,/funding-round/d205f5416ce55e126beda3ed2bf2c2cd,debt_financing,NaN,30-03-2010,250000.0
28,/organization/10-minutes-with,/funding-round/0faccbbcc5818dc5326469f13f5a8ac8,venture,A,09-10-2014,4000000.0
29,/ORGANIZATION/10-MINUTES-WITH,/funding-round/f245a74b4c54610ae843e17bdf4d1113,seed,NaN,01-01-2013,400000.0
...,...,...,...,...,...,...
114919,/ORGANIZATION/ZYNSTRA,/funding-round/dee233b3434185c14b3352034f72d798,angel,NaN,18-09-2012,2325000.0
114920,/organization/zyomyx-inc,/funding-round/4191cb5258d3863b0212d1083881da64,venture,B,30-06-2013,12000000.0
114921,/ORGANIZATION/ZYOMYX-INC,/funding-round/85443f5438bfd50104b9591eabc95c94,grant,NaN,26-03-2014,7500000.0
114922,/organization/zyomyx-inc,/funding-round/b4fce7f8a13267353d57db09099800e8,venture,NaN,11-07-2013,14219999.0
114923,/ORGANIZATION/ZYOMYX-INC,/funding-round/ea5b21da6cf999ff4d5667431fe318d7,venture,NaN,29-01-2010,555016.0
114924,/organization/zype,/funding-round/24e8134882bf6c4dcc385abba0acd5d9,seed,NaN,01-04-2015,1700000.0
114925,/ORGANIZATION/ZYPE,/funding-round/c9f5097b3617c7539aa47c8b448163be,seed,NaN,27-10-2015,1600000.0
114926,/organization/zypsee,/funding-round/472c6f7940522552fcca465b8cd3deef,seed,NaN,25-09-2013,2150000.0
114927,/ORGANIZATION/ZYPSEE,/funding-round/c67e22c5448435adaf5a2d101e449dde,seed,NaN,26-07-2013,NaN
114928,/organization/zyraz-technology,/funding-round/3c3ae0f177e01a04deea811e1828be35,private_equity,NaN,15-02-2013,20967.0
114929,/ORGANIZATION/ZYRAZ-TECHNOLOGY,/funding-round/55f33b179dd6f4516315348c1e8350c6,angel,NaN,01-01-2008,2007363.0
114930,/organization/zyraz-technology,/funding-round/c05aab2155e390066d51c6852ff61464,grant,NaN,11-09-2009,5400000.0
114931,/ORGANIZATION/ZYRAZ-TECHNOLOGY,/funding-round/e949f077c943db197f20e43c2eb8d0e6,venture,A,09-10-2009,7991547.0
114932,/organization/zyrra,/funding-round/2a13fa52848ace2760b224a350a76b40,seed,NaN,15-11-2010,445000.0
114933,/ORGANIZATION/ZYRRA,/funding-round/39baf35e59eb3efc5409cd4c5eaa50e1,seed,NaN,21-10-2010,50000.0
114934,/organization/zyrra,/funding-round/7a0fa791c96c9c447ee54662395beab9,venture,NaN,18-10-2012,140500.0
114935,/ORGANIZATION/ZYRRA,/funding-round/cc8cd96a500332d5b4f4bcbddb306099,angel,NaN,15-12-2010,875000.0
114936,/organization/zystor,/funding-round/7ea37c0ff4132b084832039a9380d34e,venture,A,16-12-2004,8500000.0
114937,/ORGANIZATION/ZYTOPROTEC,/funding-round/0c43e717298296d2fb334fb236300f6e,venture,A,29-01-2013,2686600.0
114938,/organization/zzish,/funding-round/34b560f672bebeb339a5efa3b27eae5d,grant,NaN,25-02-2015,400000.0
114939,/ORGANIZATION/ZZISH,/funding-round/4c82e18a8e3eab2647719d0fc27ead5f,angel,NaN,31-10-2014,400000.0
114940,/organization/zzish,/funding-round/73721fffc980d228f051e87422aa8732,seed,NaN,24-03-2014,320000.0
114941,/ORGANIZATION/ZZNODE-SCIENCE-AND-TECHNOLOGY-CO...,/funding-round/171693e1e07e0230defd8fddb6de4515,venture,A,01-04-2012,1587301.0
114942,/organization/zzzzapp-com,/funding-round/22ef2fafb4d20ac3aa4b86143dbf6c8e,seed,NaN,01-11-2011,7000.0
114943,/ORGANIZATION/ZZZZAPP-COM,/funding-round/6ba41360588bc6e3f77e9b50a0ebfafa,seed,NaN,01-08-2013,33149.0
114944,/organization/zzzzapp-com,/funding-round/8f6d25b8ee4199e586484d817bceda05,convertible_note,NaN,01-03-2014,41313.0
114945,/ORGANIZATION/ZZZZAPP-COM,/funding-round/ff1aa06ed5da186c84f101549035d4ae,seed,NaN,01-05-2013,32842.0
114946,/organization/eron,/funding-round/59f4dce44723b794f21ded3daed6e4fe,venture,A,01-08-2014,NaN
114947,/ORGANIZATION/ASYS-2,/funding-round/35f09d0794651719b02bbfd859ba9ff5,seed,NaN,01-01-2015,18192.0
114948,/organization/novatiff-reklam-ve-tantm-hizmetl...,/funding-round/af942869878d2cd788ef5189b435ebc4,grant,NaN,01-10-2013,14851.0

In [53]:
results0= {'Question':['Result Table'],'Answer':['1.1']}
result_table=pd.DataFrame(results0)
result_table

       Question Answer
0  Result Table    1.1

In [54]:
# Result Expected
# 1 - Unique companies in the rounds2 - 114949 rows
rounds2.drop_duplicates(subset='company_permalink', keep='first', inplace=True)
# Number of rows in the rounds2 frame
results01= {'Question':['How many unique companies are present in rounds2?'],'Answer':[rounds2.count(axis=0).head(1)]}
result01_table=pd.DataFrame(results01)
result_table=result_table.append(result01_table)
result_table

,Question,Answer
0,Result Table,1.1
0,How many unique companies are present in rounds2?,company_permalink 90247 dtype: int64

In [55]:
# 1 - Unique companies in the compannies -  rows
companies.drop_duplicates(subset='permalink', keep='first', inplace=True)
# Number of rows in the companies frame
results2= {'Question':['How many unique companies are present in companies?'],'Answer':[companies.count(axis=0).head(1)]}
results2_table=pd.DataFrame(results2)
result_table=result_table.append(results2_table)
result_table

,Question,Answer
0,Result Table,1.1
0,How many unique companies are present in rounds2?,company_permalink 90247 dtype: int64
0,How many unique companies are present in compa...,permalink 66368 dtype: int64

In [56]:
# Unique key for companies dataframe can be permalink column
companies.permalink.unique()
results3= {'Question':['Which column can be used as unique key for each company?'],'Answer':['permalink']}
results3_table=pd.DataFrame(results3)
result_table=result_table.append(results3_table)
result_table

,Question,Answer
0,Result Table,1.1
0,How many unique companies are present in rounds2?,company_permalink 90247 dtype: int64
0,How many unique companies are present in compa...,permalink 66368 dtype: int64
0,Which column can be used as unique key for eac...,permalink

In [57]:
#Yes, There are companies that are in rounds2 frome but not in companies
rounds2[~rounds2.isin(companies)].dropna(inplace=False)

,company_permalink,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
0,/organization/-fame,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,B,05-01-2015,10000000.0
3,/ORGANIZATION/-THE-ONE-OF-THEM-INC-,/funding-round/650b8f704416801069bb178a1418776b,venture,B,30-01-2014,3406878.0
4,/organization/0-6-com,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,A,19-03-2008,2000000.0
10,/organization/0xdata,/funding-round/3bb2ee4a2d89251a10aaa735b1180e44,venture,B,09-11-2015,20000000.0
28,/organization/10-minutes-with,/funding-round/0faccbbcc5818dc5326469f13f5a8ac8,venture,A,09-10-2014,4000000.0
34,/organization/1000memories,/funding-round/502bd0e50c27616995e4bdad24605ef8,venture,A,16-02-2011,2520000.0
46,/organization/1001-menus,/funding-round/645b4cd895450b8e0268027cd7813047,venture,B,04-11-2015,6602694.0
50,/organization/1001pharmacies-com,/funding-round/a21fc4d20200f43e3a25fd9cfc7c1482,venture,A,09-07-2015,8900000.0
52,/organization/1006-tv,/funding-round/b6aeb7401ec6993f92a16cbca153b600,venture,B,31-07-2014,10000000.0
55,/ORGANIZATION/100DU-TV,/funding-round/8797d60368bb0227f0d0ab4c72aef886,venture,A,07-01-2008,3000000.0
59,/ORGANIZATION/100HEALTH,/funding-round/502f558bee350299fd1ae503e5b9a124,venture,A,20-10-2015,3530000.0
73,/ORGANIZATION/10X-GENOMICS,/funding-round/563923487783bdeb5d0b7872f3d6b99a,venture,B,12-01-2015,55000000.0
74,/organization/10x-technologies,/funding-round/39c1441d5098875a925577d0f2ad3904,venture,B,12-01-2015,550000.0
80,/organization/117go,/funding-round/bbbda407fa8638d944ecfdd042230c4b,venture,B,28-04-2014,20000000.0
99,/ORGANIZATION/123FENG-COM,/funding-round/9d83084d87dc63a309c9a6fe9bf59d1b,venture,A,27-10-2015,13000000.0
105,/ORGANIZATION/12CM,/funding-round/51db8370127fb51822a3e291971ef195,venture,A,11-12-2014,1809056.0
108,/organization/1366-technologies,/funding-round/2a31dd8a0b006b341cde0f7b721008e6,venture,B,14-01-2011,2400000.0
109,/ORGANIZATION/1366-TECHNOLOGIES,/funding-round/31e8a281fe0247f5f13f7be8afe47e01,venture,C,12-12-2013,2500000.0
119,/ORGANIZATION/140-PROOF,/funding-round/2dc9ff9c590200195228ce2e153a1423,venture,A,01-07-2009,3000000.0
120,/organization/140-proof,/funding-round/3d40399001b0a2088620030afc533c83,venture,B,28-04-2011,2500000.0
132,/organization/16wifi,/funding-round/0496c258019a924b3a2da1ebaddb1f9d,venture,A,05-06-2015,16000000.0
133,/ORGANIZATION/17-MEDIA,/funding-round/f8ffde9fa822843ac6ea9b66cc615df1,venture,A,05-11-2015,10000000.0
134,/organization/170-systems,/funding-round/b84bb882ca873f5fb96535671981196d,venture,A,16-04-2002,14000000.0
135,/ORGANIZATION/17HATS,/funding-round/56195451074439e1f61fb0165d50eea1,venture,A,15-10-2015,4000000.0
137,/ORGANIZATION/17U-CN,/funding-round/1f3e644c0446dca6939bb0f679bfa5ea,venture,C,01-05-2012,1588983.0
138,/organization/17u-cn,/funding-round/275f67ca70ae24053ee00310a1472019,venture,A,01-01-2008,479014.0
140,/organization/17zuoye,/funding-round/69690484f51e15bc27ff52bfe472cd96,venture,A,01-01-2011,5000000.0
141,/ORGANIZATION/17ZUOYE,/funding-round/8d87f771e938e0f31641bd600abbafca,venture,B,01-09-2013,10000000.0
145,/ORGANIZATION/1800DIAPERS,/funding-round/5e2b8cd8ad0dcdff961fd09dee78d487,venture,B,04-12-2007,7000000.0
146,/organization/180solutions,/funding-round/e55f5f2b9ee65826cc5bf2e1cc2eec9e,venture,A,05-04-2004,40000000.0
...,...,...,...,...,...,...
114789,/ORGANIZATION/ZUMIGO,/funding-round/a56a2ed5f80dfc9974c3c183a4a6f786,venture,B,22-08-2014,6000000.0
114792,/organization/zumobi,/funding-round/7c851e1658d23b45351fb33c16a3d629,venture,A,07-05-2007,12000000.0
114794,/organization/zumper,/funding-round/6b597cf5bc96467a3577641ab8142c10,venture,A,04-03-2014,6500000.0
114799,/ORGANIZATION/ZUNIVERSITY-COM,/funding-round/a058abef15e17654e754acd8d4303af8,venture,B,10-01-2001,10000000.0
114800,/organization/zuora,/funding-round/0edaa816114e5e932f9f47de992f36e6,venture,D,16-11-2011,36000000.0
114801,/ORGANIZATION/ZUORA,/funding-round/68f1db0042a6aa40fa76a04f77b93175,venture,A,13-03-2008,6500000.0
114816,/organization/zurex-pharma,/funding-round/0102e17cf60cb579e53829b42552bfec,venture,B,02-07-2014,4099999.0
114817,/ORGANIZATION/ZUREX-PHARMA,/funding-round/571fd39c33928efba3242bc4433a3665,venture,A,22-05-2012,6200000.0
114839,/ORGANIZATION/ZUZUCHE,/funding-round/cb560b4a1b9eb067590695309cda1d02,venture,A,01-01-2011,1515151.0
114840,/organization/zvents,/funding-round/87de09b06ec97f61701c87e07d2b9cde,venture,B,30-09-2008,24000000.0
114841,/ORGANIZATION/ZVENTS,/funding-round/af717b723340256599a90f2a6ea6c1f0,venture,A,07-11-2006,7000000.0
114844,/organization/zverse-inc-,/funding-round/7b34004a3842dff9818cf0d8dad6a65a,venture,A,23-07-2015,3500000.0
114846,/organization/zvooq,/funding-round/17b7c24aa4710ec1b98b77304d6d4609,venture,A,19-08-2014,20000000.0
114852,/organization/zwipe,/funding-round/259f7f4d6b6335e2e1046e275a8a7430,venture,A,10-12-2013,3500000.0
114853,/ORGANIZATION/ZWIPE,/funding-round/9a0dbb2ceb73bb736fdd7d2e47d75e23,venture,B,13-10-2015,5000000.0
114858,/organization/zyb,/funding-round/1f95384b7527c9b7d2a0ea5fba918110,venture,A,01-09-2006,3845100.0
114861,/ORGANIZATION/ZYGA-TECHNOLOGY,/funding-round/00d2d8d0c604892594b4bd25cf7e18b8,venture,C,16-12-2013,10000000.0
114862,/organization/zyga-technology,/funding-round/043afcf26eb7a0657087c9cbc812db01,venture,D,25-09-2014,2000000.0
114883,/ORGANIZATION/ZYMERGEN,/funding-round/0f14ff055053208bd3d8eae98c9b3a28,venture,A,16-06-2015,44000000.0
114889,/ORGANIZATION/ZYMEWORKS,/funding-round/917b2ed7b99f219fcbc660c9789482d5,venture,D,22-09-2011,8100000.0
114902,/organization/zyncro,/funding-round/35310bcb0945d9d4b5ffa5482e5c87f3,venture,B,03-02-2012,2105600.0
114903,/ORGANIZATION/ZYNCRO,/funding-round/c8dd9ae33cc5d5a1d972b470a5955373,venture,A,05-04-2011,1699920.0
114906,/organization/zynga,/funding-round/1bc4f7b3a778e5abfbd7131f595f5011,venture,B,04-11-2009,15187000.0
114915,/ORGANIZATION/ZYNGENIA,/funding-round/55ec03b6fa2e812a2b4a9da5a4555752,venture,A,09-09-2010,25000000.0
114916,/organization/zynstra,/funding-round/05f43b37c270f5919578281ce803de8f,venture,B,09-07-2014,8400000.0
114917,/ORGANIZATION/ZYNSTRA,/funding-round/129127802dd48be42d6cd45f65895245,venture,A,12-09-2013,3800000.0
114920,/organization/zyomyx-inc,/funding-round/4191cb5258d3863b0212d1083881da64,venture,B,30-06-2013,12000000.0
114936,/organization/zystor,/funding-round/7ea37c0ff4132b084832039a9380d34e,venture,A,16-12-2004,8500000.0
114937,/ORGANIZATION/ZYTOPROTEC,/funding-round/0c43e717298296d2fb334fb236300f6e,venture,A,29-01-2013,2686600.0
114941,/ORGANIZATION/ZZNODE-SCIENCE-AND-TECHNOLOGY-CO...,/funding-round/171693e1e07e0230defd8fddb6de4515,venture,A,01-04-2012,1587301.0

In [58]:
results4= {'Question':['Are there companies in rounds2 which are not in companies?'],'Answer':['Yes']}
results4_table=pd.DataFrame(results4)
result_table=result_table.append(results4_table)
result_table

,Question,Answer
0,Result Table,1.1
0,How many unique companies are present in rounds2?,company_permalink 90247 dtype: int64
0,How many unique companies are present in compa...,permalink 66368 dtype: int64
0,Which column can be used as unique key for eac...,permalink
0,Are there companies in rounds2 which are not i...,Yes

In [59]:
#Merging companies frome into rounds2 frame and storing it as master_frame
master_frame=pd.concat([rounds2,companies],axis=0, ignore_index=True)
#master_frame=pd.merge(rounds2,companies, how='left',left_on='company_permalink', right_on='permalink')
master_frame.count()

category_list              63220
city                       58340
company_permalink          90247
country_code               59410
founded_at                 51147
funded_at                  90247
funding_round_code         21797
funding_round_permalink    90247
funding_round_type         90247
homepage_url               61310
name                       66367
permalink                  66368
raised_amount_usd          72589
region                     58338
state_code                 57821
status                     66368
dtype: int64

In [60]:
results5= {'Question':['Result Table'],'Answer':['2.1']}
results5_table=pd.DataFrame(results5)
result_table=result_table.append(results5_table)
result_table

,Question,Answer
0,Result Table,1.1
0,How many unique companies are present in rounds2?,company_permalink 90247 dtype: int64
0,How many unique companies are present in compa...,permalink 66368 dtype: int64
0,Which column can be used as unique key for eac...,permalink
0,Are there companies in rounds2 which are not i...,Yes
0,Result Table,2.1

In [61]:
#Averages of venture type investments
results6= {'Question':['Average Funding Amount of Venture Type'],'Answer':[master_frame[master_frame['funding_round_type']=='venture']['raised_amount_usd'].mean()]}
results6_table=pd.DataFrame(results6)
result_table=result_table.append(results6_table)
result_table

,Question,Answer
0,Result Table,1.1
0,How many unique companies are present in rounds2?,company_permalink 90247 dtype: int64
0,How many unique companies are present in compa...,permalink 66368 dtype: int64
0,Which column can be used as unique key for eac...,permalink
0,Are there companies in rounds2 which are not i...,Yes
0,Result Table,2.1
0,Average Funding Amount of Venture Type,1.08983e+07

In [62]:
#Averages of angel type investments
results7= {'Question':['Average Funding Amount of angel Type'],'Answer':[master_frame[master_frame['funding_round_type']=='angel']['raised_amount_usd'].mean()]}
results7_table=pd.DataFrame(results7)
result_table=result_table.append(results7_table)
result_table

,Question,Answer
0,Result Table,1.1
0,How many unique companies are present in rounds2?,company_permalink 90247 dtype: int64
0,How many unique companies are present in compa...,permalink 66368 dtype: int64
0,Which column can be used as unique key for eac...,permalink
0,Are there companies in rounds2 which are not i...,Yes
0,Result Table,2.1
0,Average Funding Amount of Venture Type,1.08983e+07
0,Average Funding Amount of angel Type,964923

In [63]:
#Averages of seed type investments
results8= {'Question':['Average Funding Amount of seed Type'],'Answer':[master_frame[master_frame['funding_round_type']=='seed']['raised_amount_usd'].mean()]}
results8_table=pd.DataFrame(results8)
result_table=result_table.append(results8_table)
result_table

,Question,Answer
0,Result Table,1.1
0,How many unique companies are present in rounds2?,company_permalink 90247 dtype: int64
0,How many unique companies are present in compa...,permalink 66368 dtype: int64
0,Which column can be used as unique key for eac...,permalink
0,Are there companies in rounds2 which are not i...,Yes
0,Result Table,2.1
0,Average Funding Amount of Venture Type,1.08983e+07
0,Average Funding Amount of angel Type,964923
0,Average Funding Amount of seed Type,697585

In [64]:
#Averages of private type investments
results9= {'Question':['Average Funding Amount of private_equity Type'],'Answer':[master_frame[master_frame['funding_round_type']=='private_equity']['raised_amount_usd'].mean()]}
results9_table=pd.DataFrame(results9)
result_table=result_table.append(results9_table)
result_table

,Question,Answer
0,Result Table,1.1
0,How many unique companies are present in rounds2?,company_permalink 90247 dtype: int64
0,How many unique companies are present in compa...,permalink 66368 dtype: int64
0,Which column can be used as unique key for eac...,permalink
0,Are there companies in rounds2 which are not i...,Yes
0,Result Table,2.1
0,Average Funding Amount of Venture Type,1.08983e+07
0,Average Funding Amount of angel Type,964923
0,Average Funding Amount of seed Type,697585
0,Average Funding Amount of private_equity Type,7.40341e+07